[package]
name = "kvs"
version = "0.1.0"
authors = ["zhangjian <zhangjian@shanghaitech.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
serde = "1.0.92"
serde_json = "1.0.39"
byteorder = "1.3.2"
log = "0.4.6"
env_logger = "0.6.1"

[dev-dependencies]
assert_cmd = "0.11"
criterion = "0.2.11"
predicates = "1.0.0"
rand = "0.6.5"
tempfile = "3.0.7"
walkdir = "2.2.7"
